language: cpp

before_script: ./autogen.sh
before_install:
  - eval "${MATRIX_EVAL}"

script:
  - ./configure --prefix=$PWD/local && make -j8 && make install  # build from checkoout
  - make dist && tar -zxf projectM-*.tar.gz && cd projectM-* && ./configure --prefix=$PWD/local && make -j8 && make install  # build from dist\
  - echo "PWD $PWD"
  - ls .
  - test -e src/projectM-sdl/projectMSDL
  - test -e src/libprojectM/libprojectM.la
  - test -e local/share/projectM/fonts/Vera.ttf
  - test -e local/share/projectM/shaders/blur.cg
  - test -d local/share/projectM/presets
  - test -e local/lib/libprojectM.la
  - test -e local/include/projectM.hpp

# test on GCC and Clang
matrix:
  include:
    # linux/clang
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libsdl2-dev
            - libglew-dev
            - libftgl-dev
            - libsdl2-dev
            - libdevil-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    # linux/gcc
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libsdl2-dev
            - libglew-dev
            - libftgl-dev
            - libsdl2-dev
            - libdevil-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    # osx/xcode/clang
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew update && brew install sdl2"

notifications:
  email:
    on_success: never
    on_failure: change
