language: cpp

compiler:
  - clang
  - gcc

before_script:
  - ./autogen.sh
before_install:
  - eval "${MATRIX_EVAL}"
  - if [ $TRAVIS_OS_NAME == "osx"  ]; then sudo sntp -sS time.apple.com; fi

addons:
  apt:
    packages:
      - libc++-dev
      - libsdl2-dev
      - libglm-dev
      - libgl1-mesa-dev

script:
  - ./configure $PM_OPTS --prefix=$PWD/local && make -j6 && make install  # build from checkout
  - make dist && tar -zxf projectM-*.tar.gz && cd projectM-* && ./configure $PM_OPTS --prefix=$PWD/dist_install && make -j6 && make install  # build from dist
  - echo "PWD=$PWD"
  - ls .
  - test -e src/projectM-sdl/projectMSDL
  - test -e src/libprojectM/libprojectM.la
  - test -e dist_install/share/projectM/fonts/Vera.ttf
  - test -d dist_install/share/projectM/presets
  - test -e dist_install/lib/libprojectM.la
  - test -e dist_install/include/libprojectM/projectM.hpp
  - test -e dist_install/include/libprojectM/Common.hpp
  - test -e dist_install/include/libprojectM/PCM.hpp
  - dist_install/bin/projectM-unittest

# test on GCC and Clang
matrix:
  include:
    #  pulseaudio/qt/jack
    - os: linux
      addons:
        apt:
          packages:
            - libglm-dev
            - qt5-default
            - qtdeclarative5-dev
            - libqt5opengl5-dev
            - libjack-dev
            - libpulse-dev
            - libc++-dev
            - libsdl-dev  # for jack
            - libsdl2-dev  # for tests
      env:
        - MATRIX_EVAL="PM_OPTS=\"--enable-qt --enable-jack --enable-pulseaudio --enable-sdl\""

    # osx/xcode/clang
    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="brew update && brew install sdl2 glm"

notifications:
  email:
    on_success: never
    on_failure: change
